/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\blogs\\blog-project\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-60200a2e",
    path: "/CategoryList.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-60200a2e").then(next)
    },
  },
  {
    name: "v-443c9b66",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-443c9b66").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-09ff7960",
    path: "/languageOptions/Japanese.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-09ff7960").then(next)
    },
  },
  {
    name: "v-512ffea8",
    path: "/languageOptions/Chinese.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-512ffea8").then(next)
    },
  },
  {
    name: "v-707d62d5",
    path: "/music.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-707d62d5").then(next)
    },
  },
  {
    name: "v-4c8844f0",
    path: "/guide/guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4c8844f0").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]