/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "分类列表",
      "frontmatter": {},
      "regularPath": "/CategoryList.html",
      "relativePath": "CategoryList.md",
      "key": "v-60200a2e",
      "path": "/CategoryList.html",
      "headers": [
        {
          "level": 2,
          "title": "分类列表",
          "slug": "分类列表"
        }
      ],
      "lastUpdated": "10/21/2021, 10:41:12 PM"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "Hero 标题",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2021-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-443c9b66",
      "path": "/",
      "lastUpdated": "10/21/2021, 10:41:12 PM"
    },
    {
      "title": "日文切换页面",
      "frontmatter": {},
      "regularPath": "/languageOptions/Japanese.html",
      "relativePath": "languageOptions/Japanese.md",
      "key": "v-09ff7960",
      "path": "/languageOptions/Japanese.html",
      "headers": [
        {
          "level": 2,
          "title": "日文切换页面",
          "slug": "日文切换页面"
        }
      ],
      "lastUpdated": "10/21/2021, 10:41:12 PM"
    },
    {
      "title": "简体中文切换页面",
      "frontmatter": {
        "search": false
      },
      "regularPath": "/languageOptions/Chinese.html",
      "relativePath": "languageOptions/Chinese.md",
      "key": "v-512ffea8",
      "path": "/languageOptions/Chinese.html",
      "headers": [
        {
          "level": 2,
          "title": "简体中文切换页面",
          "slug": "简体中文切换页面"
        }
      ],
      "lastUpdated": "10/21/2021, 10:41:12 PM"
    },
    {
      "title": "今日音乐推荐",
      "frontmatter": {},
      "regularPath": "/music.html",
      "relativePath": "music.md",
      "key": "v-707d62d5",
      "path": "/music.html",
      "headers": [
        {
          "level": 2,
          "title": "今日音乐推荐",
          "slug": "今日音乐推荐"
        }
      ],
      "lastUpdated": "10/21/2021, 10:41:12 PM"
    },
    {
      "title": "导航页面",
      "frontmatter": {
        "navbar": false
      },
      "regularPath": "/guide/guide.html",
      "relativePath": "guide/guide.md",
      "key": "v-4c8844f0",
      "path": "/guide/guide.html",
      "headers": [
        {
          "level": 2,
          "title": "导航页面",
          "slug": "导航页面"
        }
      ],
      "lastUpdated": "10/21/2021, 10:41:12 PM"
    }
  ],
  "themeConfig": {
    "logo": "/assets/img/logo.png",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "导航",
        "link": "/guide/guide/"
      },
      {
        "text": "分类",
        "link": "/CategoryList/"
      },
      {
        "text": "音乐",
        "items": [
          {
            "text": "中文音乐",
            "items": [
              {
                "text": "flac",
                "link": "/Chines/"
              },
              {
                "text": "mp3",
                "link": "/Chines/"
              }
            ]
          },
          {
            "text": "英文音乐",
            "items": [
              {
                "text": "flac",
                "link": "/Chines/"
              },
              {
                "text": "mp3",
                "link": "/Chines/"
              }
            ]
          }
        ]
      },
      {
        "text": "语言",
        "items": [
          {
            "text": "简体中文",
            "link": "/languageOptions/Chinese/"
          },
          {
            "text": "日文",
            "link": "/languageOptions/Japanese/"
          }
        ]
      },
      {
        "text": "外链",
        "link": "http://www.baidu.com",
        "target": "_self",
        "rel": ""
      }
    ],
    "sidebar": "auto",
    "searchMaxSuggestions": 10,
    "lastUpdated": "Last Updated"
  }
}